FROM golang:1.24-alpine AS builder

WORKDIR /app

# Копируем исходный код
COPY . .

# Собираем LLM-воркер
RUN CGO_ENABLED=0 GOOS=linux go build -o llm-worker ./cmd/neurobot

FROM alpine:latest

WORKDIR /app

# Копируем скомпилированный бинарный файл и конфигурацию
COPY --from=builder /app/llm-worker .
COPY --from=builder /app/config ./config

# Добавляем необходимые CA сертификаты и временные зоны
RUN apk --no-cache add ca-certificates tzdata

CMD ["./llm-worker", "--config", "./config", "--mode", "llm"]