FROM alpine:latest

WORKDIR /app

# Копируем предварительно скомпилированный бинарный файл
COPY llm-worker .
COPY config ./config

# Добавляем необходимые CA сертификаты и временные зоны
RUN apk --no-cache add ca-certificates tzdata

CMD ["./llm-worker", "--config", "./config", "--mode", "llm"]
