FROM alpine:latest

WORKDIR /app

# Копируем предварительно скомпилированный бинарный файл
COPY webhook-server .
COPY config ./config

# Добавляем необходимые CA сертификаты и временные зоны
RUN apk --no-cache add ca-certificates tzdata

EXPOSE 8080

CMD ["./webhook-server", "--config", "./config", "--mode", "webhook"]
